server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    # ??????? Oracle ???? 1521???????? ORCL (?????? XE)??????????
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system # ??????????
    password: 123456        # ?????????

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ?????????? (????? well_id ???? Java ? wellId)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????? SQL ????????????
    